version: "3.8"
services:
  firestore:
    image: firebase/emulator:latest
    ports:
      - "8080:8080" # Firestore port
      - "4000:4000" # Emulator UI
    volumes:
      - ./firebase-data:/firebase/data
    command:
      [
        "firebase",
        "emulators:start",
        "--only",
        "firestore",
        "--project",
        "fin-track-local",
      ]
