services:
  db:
    image: postgres:16
    container_name: fintrack-db
    restart: always
    environment:
      POSTGRES_USER: fintrack
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fintrack
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: fintrack-adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
